model_name: baseline    # name of the using model
save_name: model     # name of the saved model file, does not need to be changed

baseline:
  hidden_dim: 16
baseline_shared:
  hidden_dim: 16
sota:
  hidden_dim: 16
clip:
  hidden_dim: 16
  temperature: 0.07
  load_from_pretrained: true
  pretrained_model_path: E:/Code/SparrKULee/SparrKULee/match_mismatch/output/clip_pretrained/bsz-1024/models/model.ckpt
  freeze_grad_when_tuning: true
